repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: '22.12.0'
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: '5.11.4'
    hooks:
      - id: isort
        args:
          - --profile=black

  - repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
        args:
          - --max-line-length=88

  #  - repo: https://github.com/PyCQA/bandit
  #    rev: "1.7.4"
  #    hooks:
  #      - id: bandit
  #        exclude: tests/

  #  - repo: https://github.com/codespell-project/codespell
  #    rev: 'v2.2.1'
  #    hooks:
  #      - id: codespell

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: 'v1.3.1'
    hooks:
      - id: python-safety-dependencies-check
        stages: [manual]
        files: requirements.txt

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
